### PR TITLE
Fix sdiv implementation.

### PR DESCRIPTION
**Pull request by ptersilie**
This fixes a bug with the sdiv implementation. The reason for the bug was that I misunderstood some details about `idiv`.

### CODE REVIEW

**Comment by ltratt** [comment]
Can we add tests to x86_64/mod.rs about the generated code? Those are more robust tests than the lang_tests for these sorts of thing (and the JIT IR parser & fm incombination make creating such tests pretty easy).

**Comment by ptersilie** [comment]
I can, but it will require me to add at least 8 unit tests to get the same coverage as the langtest has now.

**Comment by ptersilie** [comment]
I improved the langtest a bit and simplified the implementation for byte-sized values. I also added a unit test. Let me know if you want me to add unit tests for the other 7 cases.

**Comment by ltratt** [comment]
In general I would love it if we unit tested all the cases, because that will really help us going forwards, but I will leave that to your discretion until yklua is running. Please squash if you want.

**Comment by ptersilie** [comment]
Squashed (I kinda wanna push on with things and look into testing later).

**Pull request merged**
