### PR TITLE
Remove the IR serialisation documentation.

### PR DESCRIPTION
**Pull request by ltratt**
This is out-of-date, and keeping it upto date is, at least until things stabilise, more effort than it's worth.

### CODE REVIEW

**Comment by vext01** [comment]
There's a reference to the removed file in `SUMMARY.md`. Then we are good.

**Comment by ltratt** [comment]
Oops! Fixed in a82af1e2.

**Comment by vext01** [comment]
Please squash.

**Comment by ltratt** [comment]
Squashed.

**Pull request merged**
