### PR TITLE
Add tests

### PR DESCRIPTION
**Pull request by Pavel-Durov**
Added a few tests.
- Indirect calls with externally linked functions and callbacks.
- Goto loop test

### CODE REVIEW

**Comment by Pavel-Durov** [comment]
When I run tests with computed gotos in YK I get this error:
```
ld.lld: ../yk/ykllvm/llvm/lib/Transforms/Yk/BlockDisambiguate.cpp:265: void {anonymous}::YkBlockDisambiguate::processFunction(llvm::LLVMContext&, llvm::Function&): Assertion `!isa<IndirectBrInst>(TI)' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
```
I guess it is for the same reason as this test is ignored: https://github.com/ykjit/yk/blob/master/tests/c/indirect_branch.c#L1

**Comment by ltratt** [comment]
@Pavel-Durov Where are we with this PR? Could it be merged?

**Comment by Pavel-Durov** [comment]
Yes, it's ready.

**Comment by ltratt** [comment]
Please squash.

**Comment by Pavel-Durov** [comment]
squashed 👉 d52a8018098207d86945596ab3c00e45e45e36f1

**Pull request merged**
