### PR TITLE
Deserialise the pointer type.

### PR DESCRIPTION
**Pull request by vext01**
Requires: https://github.com/ykjit/ykllvm/pull/87

### CODE REVIEW

**Comment by vext01** [comment]
(forgot to update the docs, added a commit for that)

**Comment by ltratt** [comment]
Please squash.

**Comment by vext01** [comment]
Ok to sync ykllvm at the same time?

**Comment by ltratt** [comment]
Yes -- but for future PRs please just include the hash of the commit in your ykllvm PR in the yk PR. That means that, in many cases (those where no squashing is done with ykllvm), we won't have to hack it in during squashing.

**Comment by vext01** [comment]
splat.

**Pull request merged**
