### PR TITLE
Less shadowstack

### PR DESCRIPTION
**Pull request by ptersilie**
Requires https://github.com/ykjit/ykllvm/pull/181.

We no longer adjust the shadowstack for external functions as there's no need to
do so. While this doesn't have a measurable performance gain, it does clean up
the IR quite a bit. So this

```
%1 = ptr_add shadowstack, 16
*shadowstack = %1
call external_func()
*shadowstack = %orig_shadowstack
```

turns into

```
call external_func()
```

The change broke a few tests which this commit fixes.

### CODE REVIEW

**Comment by ptersilie** [comment]
I've added another unrelated commit that adds two new tests. These should have gone into the side-tracing PR but I forgot to add them back then.

**Comment by ptersilie** [comment]
Ok to squash and rebase?

**Comment by ltratt** [comment]
Please squash.

**Comment by ptersilie** [comment]
Squashed and rebased.

**Pull request merged**
