### PR TITLE
Rename `JITStats`.

### PR DESCRIPTION
**Pull request by ltratt**
In retrospect this is too narrow a name. Internally the struct is now `YkStats` and the external environment names is `YKD_STATS`.

### CODE REVIEW

**Comment by vext01** [comment]
It didn't merge?

**Comment by vext01** [comment]
ah, conflicts. please resolve.

**Comment by ltratt** [comment]
This has merged OK https://github.com/ykjit/yk/commits/master. I think the PR should have closed automatically but we should close it manually?

**Comment by vext01** [comment]
that's really odd...

**Pull request closed without merging**
