### PR TITLE
Delete some old codegen tests.

### PR DESCRIPTION
**Pull request by vext01**
See commits for justification.

### CODE REVIEW

**Comment by vext01** [comment]
```
10:41:55 + ASAN_SYMBOLIZER_PATH=/ci/ykllvm/inst/../inst/bin/llvm-symbolizer RUSTFLAGS=-Z sanitizer=address cargo test -Z build-std --target x86_64-unknown-linux-gnu
10:41:55 error: "/ci/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/Cargo.lock" does not exist, unable to build with the standard library, try:
10:41:55         rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
```

Rust broken?

**Comment by ltratt** [comment]
@vext01 Please let me know when you've investigated.

**Comment by vext01** [comment]
Yikes! I was drawing a blank. Thanks.

**Comment by vext01** [comment]
This should be good to go now?

**Pull request merged**
