### PR TITLE
Add error message for floating point instructions

### PR DESCRIPTION
**Pull request by Pavel-Durov**
+ Add error message for floating point instructions

Related to https://github.com/ykjit/yklua/issues/19

### CODE REVIEW

**Comment by Pavel-Durov** [comment]
I couldn't test it yet, cause I get an error when running `mandelbrot.lua`  benchmark with `yklua`:
```
lua: src/jitmodbuilder.cc:1258: static tuple<CallInst *, size_t, Value *> JITModBuilder::GetControlPointInfo(Module *): Assertion `F->getReturnType()->isVoidTy()' failed.
Aborted (core dumped)
```

**Comment by ltratt** [comment]
This looks plausible. Can we add a test file that checks `status: error` and `stderr: Floating point instructions are not supported yet` (or similar)? I think that should go alongside the other C tests (@vext01 can shout if I'm wrong).

**Comment by Pavel-Durov** [comment]
Added test :point_right: https://github.com/ykjit/yk/pull/776/commits/4321287b47ec4ea2dce98fdb591b3eb4c342fc2b

**Comment by vext01** [comment]
LGTM. Happy if @ltratt is.

**Comment by ltratt** [comment]
Please squash.

**Comment by Pavel-Durov** [comment]
squashed :point_right: ad59c261b057bbe84af090546044bb3b36f390a7

**Comment by Pavel-Durov** [comment]
build fixed by running `cargo xtask cfmt` :point_right: https://github.com/ykjit/yk/pull/776/commits/8226307b7d86f0598417b33c9f5ff3327755ab0b

**Comment by Pavel-Durov** [comment]
bors try-

**Comment by Pavel-Durov** [comment]
bors ping

**Comment by ltratt** [comment]
Please squash.

**Comment by Pavel-Durov** [comment]
squashed 👉 2a267f19fe970bd1e2b5ae671ebce56073931940

**Pull request merged**
