### PR TITLE
Add the void type.

### PR DESCRIPTION
**Pull request by vext01**
See commits.

Required compiler change ~~coming soon~~: https://github.com/ykjit/ykllvm/pull/85

### CODE REVIEW

**Comment by ltratt** [comment]
> if the instruction's type is not void, it makes a value.

What does "makes a value" mean? "Produces a value" or ... ? And what do we mean by "value"? It would be good if we can define these terms here for ourselves so that we're not dependent on LLVM and its (sometimes quirky, often changing...) terminology.

**Comment by vext01** [comment]
By "makes a value" I mean the instruction returns something, and thus defines a new local variable.

We can define stuff if we like, but right now it's all the same as LLVM. I'm also not 100% sure I'm ready to write that sort of stuff down until we've gotten a little further in the design. Can we delay it a bit?

**Comment by ltratt** [comment]
> By "makes a value" I mean the instruction returns something, and thus defines a new local variable.

Are we saying that it literally defines a variable (as, I believe, LLVM does) or that its result must be assigned to a variable?

> We can define stuff if we like, but right now it's all the same as LLVM. I'm also not 100% sure I'm ready to write that sort of stuff down until we've gotten a little further in the design. Can we delay it a bit?

OK.

**Comment by vext01** [comment]
> Are we saying that it literally defines a variable (as, I believe, LLVM does) 

Correct.

In LLVM IR, any instruction starting `%blah =` defines a variable, and the way you'd check that using the LLVM API is to ask if the instruction is of type void. I'm doing exactly the same here for now.

**Comment by ltratt** [comment]
OK, let's worry about the design of this when we've got some more experience.

bors r+

**Comment by vext01** [comment]
(we also need the compiler change to be merged first, and then we have to sync it here)

**Comment by vext01** [comment]
synced ykllvm. ok to squash?

**Comment by ltratt** [comment]
Please squash.

**Comment by vext01** [comment]
splat.

**Pull request merged**
