### PR TITLE
Parse JIT IR for constant pointers.

### PR DESCRIPTION
**Pull request by ltratt**

### CODE REVIEW

**Comment by ptersilie** [comment]
Please squash.

**Comment by ltratt** [comment]
Squashed.

**Comment by ltratt** [comment]
Ah the JIT IR syntax changed. Fixed in https://github.com/ykjit/yk/pull/1223/commits/7fa89bb4edbe639c87f86da00e15a949294d4003. OK to squash?

**Comment by ptersilie** [comment]
Please squash.

**Comment by ltratt** [comment]
Squashed.

**Pull request merged**
