### PR TITLE
Deserialise function types and argument operands.

### PR DESCRIPTION
**Pull request by vext01**
Companion to https://github.com/ykjit/ykllvm/pull/95

### CODE REVIEW

**Comment by ltratt** [comment]
Please force push an update with the new ykllvm and commit and "Derserialise" -> "Deserialise" in the commit message title.

**Comment by vext01** [comment]
Done.

**Comment by vext01** [comment]
Fixed the test, and spotted `dbg!`s that we missed!

**Comment by ptersilie** [comment]
Please squash.

**Comment by vext01** [comment]
Thread Sanitiser.

Retry?

**Comment by ltratt** [comment]
You'll be pleased to know I have a PR coming which, at least in my testing, heavily reduces thread sanitiser issues!

bors r+

**Comment by vext01** [comment]
That's a new one on me:

> command timed out: 1200 seconds without output running [b'git', b'submodule', b'update', b'--init', b'--recursive'], attempting to kill

retry?

**Comment by ltratt** [comment]
Probably a network oddity.

bors r+

**Comment by vext01** [comment]
That weird mold error again.

Can we retry?

**Comment by ltratt** [comment]
I'll try once more, but if this happens again, we're either going to have to try upgrading mold or use another linker...

bors r+

**Comment by ltratt** [comment]
@vext01 Something odd is going on here, and I don't think another r+ is going to fix it.

**Comment by vext01** [comment]
OK, let me see if I can reproduce it.

**Comment by vext01** [comment]
Asides from the obvious linker error, there's also this:

```
11:10:09   [3539/5765] Building CXX object lib/Target/X86/CMakeFiles/LLVMX86CodeGen.dir/X86ISelLowering.cpp.o
11:10:09   ninja: build stopped: subcommand failed.                            
11:10:09                                                                       
11:10:09   --- stderr                                                          
11:10:09   CMake Warning:                                                      
11:10:09     Ignoring extra path from command line:                            
11:10:09                                                                       
11:10:09      "/ci/target/release/ykllvm/build/CMAKE_C_COMPILER=/usr/bin/clang"
11:10:09                                                                       
11:10:09                                                                       
11:10:09   CMake Warning:                                                      
11:10:09     Ignoring extra path from command line:                            
11:10:09                                                                       
11:10:09      "CMAKE_CXX_COMPILER=/usr/bin/clang++"                            
11:10:09                                                                       
11:10:09                                                                       
11:10:09   thread 'main' panicked at ykbuild/build.rs:191:43:                  
```

This is the second time the repo is built, using the submodule build system...

**Comment by ltratt** [comment]
Has this PR (and/or ykllvm?) changed something relevant? Because I've never seen that before, and it seems relatively unlikely that some long-standing error has suddenly caused three build failures in a row just for this PR.

**Comment by vext01** [comment]
I've never seen it before either. I don't believe I've changed anything with the build system. If I have it was unintentional.

Investigating...

**Comment by vext01** [comment]
bors try

**Comment by vext01** [comment]
OK good. Took ages to track down.

What was happening was, the left in ykllvm debug code (that we recently [killed in a PR](https://github.com/ykjit/ykllvm/pull/96)) used `Type::dump()`, which is only present if LLVM is built with assertions enabled. Syncing ykllvm to after we killed that debug code therefore fixes this.

So dumb question: how did this slip into ykllvm? The ykllvm CI always builds *with* assertions enabled.

It's useful to test with assertions on, so should we test that ykllvm at least *builds* without assertions? Will obviously slow the CI run a little, but probably worthwhile?

OK to squash this PR?

**Comment by ltratt** [comment]
> It's useful to test with assertions on, so should we test that ykllvm at least builds without assertions?

Agreed: we should definitely add that check to stop this happening again!

Please squash.

**Comment by vext01** [comment]
splat.

and i'll do a PR for the ykllvm CI when I get a moment.

**Comment by ltratt** [comment]
> and i'll do a PR for the ykllvm CI when I get a moment.

Thanks!

bors r+

**Pull request merged**
