### PR TITLE
Codegen PHI nodes.

### PR DESCRIPTION
**Pull request by vext01**
For this we introduce a new JIT opcode "assign", which is used to select the correct incoming value at trace construction time.

ykllvm PR ~~coming soon~~: https://github.com/ykjit/ykllvm/pull/148

### CODE REVIEW

**Comment by ltratt** [comment]
Can we/should we have a test which unrolls loops? That will also use phi nodes and might be a useful test. If it doesn't yet work, then it might be worth making it the subsequent PR(s)?

**Comment by vext01** [comment]
> Can we/should we have a test which unrolls loops? 

No idea if that works or not, but I can investigate.

**Comment by ltratt** [comment]
@vext01 Shall I kick this one off for a merge anyway? We can fix things in a follow-up PR if necessary.

**Comment by vext01** [comment]
Sure, if that's OK by you.

**Pull request merged**
