### PR TITLE
Add a (failing) test for "foreign reentrant" code.

### PR DESCRIPTION
**Pull request by vext01**
As requested yesterday :)

### CODE REVIEW

**Comment by vext01** [comment]
@ptersilie just remembered @ltratt is away today. Do you wanna look at this?

**Comment by ptersilie** [comment]
Looks good to me.

**Comment by vext01** [comment]
I did wonder this. We would need to think about if it's possible for foreign code to jump (or call) to the return address of the call to the foreign code. This is the only source of ambiguity I can think of.

In general foreign code can do anything it wants of course...

**Comment by ltratt** [comment]
I think the "right" check is that a) we're back to the same source location and b) the same stack address. [The latter condition solves the "got back to the same source location because of e.g. a recursive call".]

bors r+

**Comment by ltratt** [comment]
> So we'd have to keep some kind of abstract stack pointer, and update it based upon the instruction stream.

Yes.

>Even then, if the stack pointer is updated using some dynamic value (e.g. mov rsp, [r11]) we would be in trouble.

Anyone doing that gets what they deserve!

**Pull request merged**
