### PR TITLE
Put back ignored tests

### PR DESCRIPTION
**Pull request by vext01**
Phase one of re-enabling ignored tests (and adding some new related ones).

This requires a compiler-side change, which I can't raise until https://github.com/ykjit/ykllvm/pull/23 is merged. We can still review it now.

### CODE REVIEW

**Comment by ltratt** [comment]
Typo "requiured" in b012ba213adad64de3ef5277d0f426014dfb3bb5's commit message. Please force push an update.

**Comment by vext01** [comment]
OK, i'll do that at the end.

**Comment by vext01** [comment]
@ptersilie any comments?

**Comment by ptersilie** [comment]
Apart from the "requiured" that Laurie already pointed out, this looks good to me.

**Comment by ltratt** [comment]
Please force push an update.

**Comment by vext01** [comment]
splat.

**Comment by vext01** [comment]
I think we will need to re-run this, as buildbot crashed recently, killing all build jobs.

**Pull request merged**
