### PR TITLE
Merge ykdocs

### PR DESCRIPTION
**Pull request by ltratt**
This merges the ykdocs repository into yk, with most of the content coming under the `docs` directory.

There are 3 main commits (in order):

1. https://github.com/ykjit/yk/commit/b098c196b2416461851230f7d2510b5e8eb11fe2 moves ykdocs content into a `docs` subsdirectory.
2. https://github.com/ykjit/yk/commit/a3c3a27c0c42120cc85cf05952552bdbee2f2cf1 merges ykdocs into this branch.
3. https://github.com/ykjit/yk/commit/ec920fdeaee65b66df297a506ae2d80616ce1555 adds a check of the docs to `.buildbot.sh`

### CODE REVIEW

**Comment by ltratt** [comment]
bors try

**Comment by ltratt** [comment]
I should have said: joint work with @pavel-durov.

**Comment by vext01** [comment]
Thanks for doing this.

Any squashing?

**Comment by vext01** [comment]
That's something we should be able to handle with lang_tester's new features.

**Pull request merged**
