### PR TITLE
Expose `ar(1)` and `ranlib(1)` in yk-config.

### PR DESCRIPTION
**Pull request by vext01**
Required to fix yklua warnings.

yklua PR that explains: https://github.com/ykjit/yklua/pull/24

### CODE REVIEW

**Comment by Pavel-Durov** [comment]
please squash

**Comment by vext01** [comment]
No squashing required.

**Comment by Pavel-Durov** [comment]
ah then I just do bors stuff.. ok

**Comment by Pavel-Durov** [comment]
bors try

**Pull request merged**
