### PR TITLE
Honour the `yk_outline` function annotation.

### PR DESCRIPTION
**Pull request by vext01**
Companion to https://github.com/ykjit/ykllvm/pull/28.

See commits.

### CODE REVIEW

**Comment by ltratt** [comment]
Please squash.

**Comment by vext01** [comment]
splat.

**Comment by ltratt** [comment]
Can you rebase against master and force push?

**Comment by vext01** [comment]
rebased and fixed a typo (hence second force push -- my bad).

**Comment by vext01** [comment]
This one is ready to go now.

**Pull request merged**
