### PR TITLE
Break the testing code into its own module.

### PR DESCRIPTION
**Pull request by ltratt**
This partly addresses https://github.com/ykjit/yk/issues/510. I got most of the way through following this through for the stopgap code in ykcapi before realising that I'd create a merge conflict nightmare for https://github.com/ykjit/yk/pull/500/. I therefore think it's best wait until that PR is merged before messing with the stopgap code in ykcapi.

### CODE REVIEW

**Comment by vext01** [comment]
So this part is OK to merge now?

**Comment by ltratt** [comment]
If you're happy with it, I'm happy with it!

**Comment by ltratt** [comment]
I'm an idiot -- OK to squash?

**Comment by vext01** [comment]
On Tue, Mar 01, 2022 at 02:10:19AM -0800, Laurence Tratt wrote:
> I'm an idiot -- OK to squash?

Please squash.

-- 
Best Regards
Edd Barrett

https://www.theunixzoo.co.uk

**Comment by ltratt** [comment]
Squashed.

**Pull request merged**
