### PR TITLE
Add the new -yk-linkage flag to yk-config.

### PR DESCRIPTION
**Pull request by vext01**
Depends on https://github.com/ykjit/ykllvm/pull/62

### CODE REVIEW

**Comment by vext01** [comment]
Shall I rebase this one too?

**Comment by ltratt** [comment]
Please rebase.

**Comment by vext01** [comment]
Rebased, but don't forget to merge https://github.com/ykjit/ykllvm/pull/62 first.

**Comment by vext01** [comment]
This is  ready to go now.

**Pull request merged**
