### PR TITLE
Import hwtracer into yk.

### PR DESCRIPTION
**Pull request by vext01**
It took a few attempts, but this merges the hwtracer into the yk repo.

Mostly unreviewable. You only want to look at these commits:

Preparation for import:

 - 6474435e1efe8107e59c0b0f2f791e31b63c9bb7

Then `c23a3d157854b2b7d91d7d908aeda37d432b349d` is the merge commit that actually does the import.
 
Post-import:
 - cb28822060976d5236ccd0f79647b2fd7414d4d3
 - a01d40b11947aad61177f71e64e9fed126091709
 - b6f1549d3848021938ff5ec594e5496f5bad1c68
 - 2786b6a3b622faba7d14f38dc7de0297744bc85c
 - 3d52130c4c3b71e1a0071b75e271823332ec7a37
 - c512be7474cd456851644f9d27663c112a0e3dd3
 - 9d8173e261d7e750d312e8c8a848cc9165b902ef
 - 0da6a4ede178b78e6e63d5d673a134dc56a93f5e 

(I see that I started work on our JIT in November 2017 -- 5 years ago!)

### CODE REVIEW

**Comment by vext01** [comment]
bors try

**Comment by vext01** [comment]
By the way, I was on the fence with https://github.com/ykjit/yk/commit/0da6a4ede178b78e6e63d5d673a134dc56a93f5e. This reformats all of hwtracer's C code using `yk`'s `xtask cfmt`.

Since very few people will have cloned our code, I'm ok with it.

**Comment by ltratt** [comment]
You've done everything in the move that I can think of! If there are things we later find need tweaking, we can do so in future PRs.

bors r+

**Comment by vext01** [comment]
I had better kill my `try`.

bors try-

**Pull request merged**
