### PR TITLE
Implement zero extend.

### PR DESCRIPTION
**Pull request by ptersilie**

### CODE REVIEW

**Comment by vext01** [comment]
Please squash

**Comment by ptersilie** [comment]
Squashed.

**Comment by ptersilie** [comment]
Don't merge yet. Forgot to push the ykllvm change.

**Comment by ptersilie** [comment]
Here it is: https://github.com/ykjit/ykllvm/pull/156

**Comment by ltratt** [comment]
Please force push an update with the updated ykllvm commit.

**Comment by ptersilie** [comment]
Done.

**Comment by ptersilie** [comment]
Hold on. Something's broken.

**Comment by ptersilie** [comment]
Nevermind. My ykllvm checkout didn't rebuilt properly. This PR should be fine.

**Pull request merged**
