### PR TITLE
Clippy fixes

### PR DESCRIPTION
**Pull request by ltratt**

### CODE REVIEW

**Comment by vext01** [comment]
I see what you mean about `Option`. Somehow a `Result` carries more imperative, but whatever :P

So I would say "bors r+", but I guess now I ask "are you sure CI would pass?" :laughing:

**Comment by ltratt** [comment]
> Are you sure CI would pass?

I'll need to rebase and force push to know if everything works on master. OK?

**Comment by vext01** [comment]
go ahead.

**Comment by ltratt** [comment]
Confirmed passing.

**Pull request merged**
