### PR TITLE
Handle (non-debug) intrinsics.

### PR DESCRIPTION
**Pull request by vext01**
If a call to an intrinsic generates code, it is inlined. This means that
there are never IR blocks for a callee frame. In this case we can simply
continue with the current block.

Co-authored-by: Lukas Diekmann <lukas.diekmann@gmail.com>

### CODE REVIEW

**Comment by ltratt** [comment]
Are we sure this is true for all intrinsics?

I also found the description hard to make sense of. I think it might better be something like "Intrinsics generate code *within* the current function rather than being turned into a call. If we see a 'call' to an intrinsic, we assume it will not lead to a call in the eventual machine code, and that it will simply be inlined within the current basic block. Note that this means a 'call' to an intrinsic does not necessarily or start or end a basic block." ?

**Comment by vext01** [comment]
> Are we sure this is true for all intrinsics?

Lukas may have found a counter-example. Watch this space.

**Comment by ltratt** [comment]
I think we might want to close this PR?

**Comment by vext01** [comment]
I think so too. @ptersilie is that your understanding too?

**Comment by ptersilie** [comment]
No why? This is still a fix we'll need even with all the codegen optimisations disabled.

**Comment by ltratt** [comment]
Fair enough. But do we then know that all intrinsics always inline code?

**Comment by ptersilie** [comment]
> Fair enough. But do we then know that all intrinsics always inline code?

Unfortunately, to that I don't currently have an answer.

**Comment by ltratt** [comment]
What we *could* do if we're not entirely sure about *all* intrinsics is have a white-list where we only let through intrinsics that we know are inlined. But, yes, having a look at this would be great, thanks!

**Comment by ltratt** [comment]
@vext01 I think this PR is probably dead?

**Comment by vext01** [comment]
Probably, but it depends on if what @ptersilie is working on now works or not.

@ptersilie shall I close this?

**Comment by ptersilie** [comment]
Yeah, let's close it. We can still look at it later for reference if needed.

**Pull request closed without merging**
