### PR TITLE
Fix tests.

### PR DESCRIPTION
**Pull request by ltratt**
These should always have had the `%` character in the patterns, but this wasn't noticed because of a bug in fm.

### CODE REVIEW

**Comment by vext01** [comment]
Adding `%` is probably OK here as long as you don't expect to match a constant or global variable.

Note that the matcher uses only `{{}}` and we use `%{{}}` to match a local variable (because locals are prefixed `%`).

So tests containing things like `{{4}}` are actually fine, but could be more general than necessary. If you see what I mean?

If the tests pass, I'm OK with it. We probably meant to match local variables anyway.

**Comment by ltratt** [comment]
Without this PR the tests literally no longer pass when fm is fixed. The tests should *always* have had a `%` prefix, but we got away without it solely because of the fm bug.

**Comment by vext01** [comment]
Oh! In that case I think I've been leaning on this bug for what I thought was correct behavior!

**Comment by ltratt** [comment]
OK, I need to work out how to run some more tests that I didn't notice, and which now fail. Bear with.

**Comment by ltratt** [comment]
6a1c5deb fixes another test (this time a missing `$`). OK to squash?

**Comment by vext01** [comment]
ok

**Comment by ltratt** [comment]
Squashed.

**Pull request merged**
