### PR TITLE
Fix an indexing bug.

### PR DESCRIPTION
**Pull request by vext01**
@ptersilie tasked me with finding out why `puts()` doesn't work in JITted code.

 - The first commit gave me some more tooling that helped me find the bug fixed in the third commit.
 - The second commit is something I noticed along the way.

`puts()` still doesn't work, but it's broken in one less way, and we should get the fix in now in case it fixes what @ptersilie is looking at now.

### CODE REVIEW

**Comment by ltratt** [comment]
@ptersilie Does it fix your problem?

**Comment by ptersilie** [comment]
Nope.

**Comment by ptersilie** [comment]
@vext01 If I cherry-pick the third commit I get this error:
```
thread '<unnamed>' panicked at ykrt/src/compile/jitc_yk/codegen/x86_64.rs:381:74:
called `Option::unwrap()` on a `None` value
```

This happens it the codegen tries to dlsym the `.str` global. Have you seen this when making this change?

**Comment by vext01** [comment]
I'm working on a fix for that now. In this branch that error is expected by the test.

**Comment by vext01** [comment]
What's the status of this? Any objections?

**Comment by ltratt** [comment]
Please force push an update.

**Comment by vext01** [comment]
Fixed the conflicts.

Please check this error handling is OK: https://github.com/ykjit/yk/pull/1043/commits/8a6bd58e8d6a95601238de8955bdecf3a47df39c#diff-2d8235b02f7af5cbc0cef1cf9b9789aaf37ee8bee882f4bd0f9c266e1d142edbR105

And https://github.com/ykjit/yk/pull/1043/commits/ece34410c1e8bee5bb2eca86debb4546e6731185 is new -- check you are OK with that before merge.

**Comment by vext01** [comment]
Hrm, this doesn't reproduce locally.

**Comment by ltratt** [comment]
Try trci? It's super fast!

**Comment by vext01** [comment]
https://github.com/ykjit/yk/pull/1043/commits/919c0bf4ccab549c5c5bd5845dd90d5caea428c8 fixes this.

software tracing gets further so the output doesn't look the same. I've skipped this on sw tracing for now.

There are two other commits. I will need to squash.

**Comment by ltratt** [comment]
Please squash.

**Comment by vext01** [comment]
splat.

**Comment by vext01** [comment]
OK, I finally tracked this down.

The [first commit](https://github.com/ykjit/yk/pull/1043/commits/6da359a981f2f84637d1e6698c54c8d2e4f56425) avoids UB that occurs when we execute past the end of the JITted code.

The second fixes a bogus sequence of `ignore-if` lines in the newcg test.

Tested on tryci.

OK to squash?

**Comment by ltratt** [comment]
Please squash.

**Comment by vext01** [comment]
squashed.

**Pull request merged**
