### PR TITLE
Serialise types later.

### PR DESCRIPTION
**Pull request by vext01**
We must serialise types last, as constants could introduce new types.

Extended test to cover this possibility.

Had to use `const`s instead of enums with unit variants for the type and constant kinds, as `MyEnum::MyVariant as u8` doesn't work inside `#[deku(id = "...")]`.

### CODE REVIEW

**Comment by vext01** [comment]
OK for me to force push the rebase/resolution?

**Comment by ltratt** [comment]
Please force push a rebase.

**Comment by vext01** [comment]
pushed.

**Pull request merged**
