### PR TITLE
Better test and document `IntegerTy::make_constant()`

### PR DESCRIPTION
**Pull request by vext01**
Lukas has a crash related to this routine.

I've reviewed it, checked it does what I think (it does), documented it and tested it better.

(Not fixing the crash just yet, as it requires some unmerged stuff lukas is working on to repro)

### CODE REVIEW

**Comment by ltratt** [comment]
Looking at this, I think this is an unrelated PT decoder thing. It might be worth looking into that separately but I'm going to try remerging the PR.

**Comment by vext01** [comment]
OK to force push conflict fixes?

**Comment by ltratt** [comment]
Please go ahead.

**Comment by vext01** [comment]
rebased.

**Comment by vext01** [comment]
OK to squash/rebase?

**Comment by ltratt** [comment]
Please squash.

**Comment by vext01** [comment]
squashed.

**Pull request merged**
