### PR TITLE
Deal with indirect function calls.

### PR DESCRIPTION
**Pull request by ptersilie**
This implements ways to deal with function calls, where the callee isn't
statically known, e.g.

%1 = @foo
call %1

Since at the time we trace the call instruction we can't tell what %1
is, we need to look ahead in the trace which function the tracer saw
next.

There's two scenarios we have to deal with: if we have IR for the passed
function, we can inline it as usual (note that in the future we don't
want to do this unless the function was promoted); if we don't have IR,
we can't inline and leave the call as is (we do however need to make
sure that the called function has been redeclared in the JITModule).

### CODE REVIEW

**Comment by ptersilie** [comment]
Just realised that my description didn't make sense. Fixed in the PR comment, but will have to reword the first commit during rebase later.

**Comment by ltratt** [comment]
Can we be consistent with terminology? We use (at least) "function pointers", "indirect calls", and "dynamic calls" in different places I think. FWIW, I think "indirect calls" is probably the best term.

**Comment by ptersilie** [comment]
> Can we be consistent with terminology? We use (at least) "function pointers", "indirect calls", and "dynamic calls" in different places I think. FWIW, I think "indirect calls" is probably the best term.

Okay, will fix, some of it during rebasing.

**Comment by ltratt** [comment]
> Okay, will fix, some of it during rebasing.

What would be fixed during rebasing?

**Comment by ltratt** [comment]
> Function pointer is correct here.

But every call is to a function pointer. So there must surely be something different about this PR (although now you've got me wondering!).

**Comment by vext01** [comment]
> But every call is to a function pointer.

A static call doesn't involve a function pointer.

[At the asm level, `call myfunc` (direct) vs. `call [rax]` (indirect via func ptr stored in a register)]

Or did I get the wrong end of the stick?

**Comment by ltratt** [comment]
OK, so offline I think we've agreed that at least the first commit needs to be clear this is about "indirect calls" i.e. function calls to a dynamically determined address.

**Comment by ptersilie** [comment]
The latest commits try to clean up the terminology a bit. Will fix the commit messages during rebasing.

**Comment by ptersilie** [comment]
@ltratt Try that last commit.

**Comment by vext01** [comment]
Some of my comments are unaddressed.

**Comment by ptersilie** [comment]
Which ones? I think I've addressed all. Try refreshing a few times. ;-)

**Comment by ptersilie** [comment]
Ready to squash?

**Comment by vext01** [comment]
Go ahead.

**Comment by ptersilie** [comment]
Squashed, rebased, and commit messages updated.

**Comment by vext01** [comment]
Needs fmt.

**Comment by ptersilie** [comment]
Fixed.

**Pull request merged**
