### PR TITLE
Don't execute code in the location transition function

### PR DESCRIPTION
**Pull request by ltratt**
This PR is a vital step in allowing us to test the location state machine.

### CODE REVIEW

**Comment by ltratt** [comment]
> Does starting/stopping traces, and spawning compilation threads not need to be moved outside too?

Possibly, but I'm not sure yet -- and I know the change in this PR *has* to be done. If we're happy with this PR, I think doing the other things will become much easier once we've established a precedent.

**Comment by vext01** [comment]
I'm happy with it, but I don't see how you can test the state machine in isolation if those events are baked in to state transitions.

**Comment by ltratt** [comment]
You're probably right that tracing needs to be moved out, though compiling in a thread probably doesn't need to be. But I think we can put off thinking about those until I actually start adding a test suite in. Clearly, this PR is a necessary (but perhaps not sufficient) step towards doing that.

**Comment by vext01** [comment]
> though compiling in a thread probably doesn't need to be.

But if you leave the compilation in, then you have the requirement to have something to trace and compile. That's going to be annoying if all you want to test is the state machine, isn't it?

> Clearly, this PR is a necessary (but perhaps not sufficient) step towards doing that.

Of course, we are in agreement there.

Any squashing to do?

**Comment by ltratt** [comment]
No squashing needed.

**Pull request merged**
