### PR TITLE
yk_control_point() must be called in a loop.

### PR DESCRIPTION
**Pull request by vext01**
Add a test that checks the compiler will reject programs which do not
call the control point in an outer loop.

Also fix a test which didn't call the control point in a loop.

Requires: https://github.com/ykjit/ykllvm/pull/20

### CODE REVIEW

**Comment by vext01** [comment]
A few extra commits to review there. Changes in response to changes on the compiler side, and some tidying.

**Comment by ltratt** [comment]
I'm not a fan of `ctrl_pt` -- can we use `control_point` for the name? I've found descriptive test names (which means descriptive file names... I know!) are useful in the long term because there's no way I'll remember to grep for `ctrl_pt`!

**Comment by vext01** [comment]
Those two commits do the renaming. Separate, because one of the tests was introduced in the previous PR and shouldn't be squashed in.

**Comment by vext01** [comment]
OK to squash this one?

**Comment by ltratt** [comment]
Please squash.

**Comment by vext01** [comment]
splat

**Pull request merged**
