### PR TITLE
Remove the libipt backend.

### PR DESCRIPTION
**Pull request by vext01**
The ykpt decoder is working well for us, and maintaining two backends is stifling productivity. It has served us well.

This comes with the caveat that we lose the hwtracer_ykpt test suite. This was a test suite that tested the ykpt backend by using the libipt backend as an oracle.

Then again, the libipt backend has been disabled for some time (it doesn't yet track the stack height when traversing unmapped code, so as to determine if re-encountering mapped code is a return or a callback).

Hopefully our other tests will serve to (indirectly) test the ykpt decoder, but later we may need to think about how to better test the ykpt decoder...

### CODE REVIEW

**Comment by ltratt** [comment]
Please force push a rebase.

**Comment by vext01** [comment]
That was odd. There was no merge conflict... I think you said you saw something like this recently too?

Try again?

**Comment by ltratt** [comment]
Yep, I've seen this too. Dunno why.

bors r+

**Comment by vext01** [comment]
The hwtracer example can't work with the ykpt decoder.

It's OK, I don't think the example adds much value anyway.

Try [74bf922](https://github.com/ykjit/yk/pull/692/commits/74bf922af76c0b8671e3f6c91512cc77cf85eb37)

**Comment by ltratt** [comment]
Agreed. Please squash.

**Comment by ltratt** [comment]
@vext01 You might have missed this one?

**Comment by vext01** [comment]
splat

**Comment by vext01** [comment]
There was still a reference to the example in the buildbot instructions. Killed in [80a289c](https://github.com/ykjit/yk/pull/692/commits/80a289cc064cb44ef8c4c653468867e9047280e9)

OK to squash?

**Comment by vext01** [comment]
(and rebase while we are here?)

**Comment by ltratt** [comment]
Please squash and rebase.

**Comment by vext01** [comment]
rebased and' splatted

**Comment by vext01** [comment]
OK to squash again :P

**Comment by ltratt** [comment]
Please squash and rebase.

**Comment by vext01** [comment]
splat and rebase.

**Comment by vext01** [comment]
I deleted too much. [dfc4d86](https://github.com/ykjit/yk/pull/692/commits/dfc4d8612f7138eb76fcba077957674ea97bc4cf) fixes this.

OK to squash yet again?

**Comment by vext01** [comment]
OK to squash?

**Comment by ltratt** [comment]
Please squash.

**Comment by vext01** [comment]
splat.

**Pull request merged**
