### PR TITLE
Fix (and check) building without `yk_jitstate_debug` works.

### PR DESCRIPTION
**Pull request by vext01**
See individual commits.

### CODE REVIEW

**Comment by ltratt** [comment]
The commit message for https://github.com/ykjit/yk/pull/577/commits/9372f54b8efb9c89dfbec30dd1893674b621e08c makes my head hurt. Can we rephrase it? [Obviously only at squashing time!]

**Comment by vext01** [comment]
How about just:

```
This fixes two related things:

 - If you were to do `cargo build -p ykcapi`, then you'd get build error
   because one import of (and call to) `print_jit_state()` wasn't
   properly guarded.

 - After fixing the above, some imports become redundant when the
   feature is off, and thus also need to be guarded.
```

**Comment by ltratt** [comment]
Does "If you were to do" mean "Before this commit this was the behaviour"?

**Comment by vext01** [comment]
That's right.

**Comment by ltratt** [comment]
Can we be clearer about that? Even just to say "Previously, `cargo build -p ykcapi` caused a build error since a `print_jit_state()` was accidentally compiled in." or similar?

**Comment by ltratt** [comment]
"get A build error" -- otherwise, works for me!

Annoyingly, one comment I made elsewhere has got stuck in github's interface (it says "pending" but...) so I'll paste it here: line 36 of `.buildbot.sh` has, I think, pointless `\` chars?

**Comment by vext01** [comment]
Fine by me.

OK to squash and fix that then?

**Comment by ltratt** [comment]
Let's push a commit for the fix (it's a habit I like :)) and then I'm sure we can soon squash!

**Comment by vext01** [comment]
You mean push an empty commit with the corrected commit message?

**Comment by vext01** [comment]
Ah, i see what you mean, sorry. Try [4e61a0b](https://github.com/ykjit/yk/pull/577/commits/4e61a0be96334baf9c9c7f0ccfcf69bc91ab7ee5)

**Comment by ltratt** [comment]
Please squash.

**Comment by vext01** [comment]
splat.

**Comment by ltratt** [comment]
Please squash (also you probably want to rebase against master at the same time).

**Comment by vext01** [comment]
done.

**Pull request merged**
