### PR TITLE
Basic floating point support.

### PR DESCRIPTION
**Pull request by vext01**
This gives us just enough floating point support to print a float value in a test.

We only support the common floating point types: float and double.

Requires https://github.com/ykjit/ykllvm/pull/175

### CODE REVIEW

**Comment by ltratt** [comment]
This looks good but could we quickly add:

* syntax tests in `jit_ir::parser::test::all_jit_ir_syntax`
* well-formedness checks in `well_formedness.rs` (i.e. `should_panic` tests)

Both well make it less likely we accidentally break things in the future :)

**Comment by vext01** [comment]
ah, sorry, wasn't aware of those tests. Yep, will add some.

**Comment by vext01** [comment]
I just realised that i accidentally re-used an old branch unintentionally! Never mind, it should be ok.

**Comment by vext01** [comment]
https://github.com/ykjit/yk/pull/1258/commits/33b8901951a78019c98cb95d76b1eee065d29102 adds tests (and strengthens some checks).

OK to squash.

**Comment by ltratt** [comment]
Please squash.

**Comment by vext01** [comment]
squashed.

**Comment by vext01** [comment]
This is a strange error:
```
11:36:58      Running `target/debug/xtask cfmt --check`
11:36:58 ./tests/c/double.newcg.c:51:46: error: code should be clang-formatted [-Wclang-format-violations]
11:36:58     fprintf(stderr, "%d -> %f\n", i, (double) i);
11:36:58                                              ^
11:36:58 
11:36:58 ./tests/c/float.newcg.c:53:45: error: code should be clang-formatted [-Wclang-format-violations]
11:36:58     fprintf(stderr, "%d -> %f\n", i, (float) i);
11:36:58                                             ^
11:36:58 
```

I am unable to reproduce it, but also the error is really generic and doesn't actually say what the problem is.

Any ideas?

**Comment by vext01** [comment]
Sorry, I got it. I was on the wrong commit. It wants me to remove the space between the cast.

**Comment by vext01** [comment]
Force pushed the fix.

**Pull request merged**
