### PR TITLE
Implement sign extension

### PR DESCRIPTION
**Pull request by vext01**
Third commit is the main work.

ykllvm PR ~~coming in a moment~~: https://github.com/ykjit/ykllvm/pull/140

### CODE REVIEW

**Comment by vext01** [comment]
OK to squash?

**Comment by vext01** [comment]
done.

**Comment by vext01** [comment]
splat.

**Comment by vext01** [comment]
Ugh, sorry. OK to squash?

**Comment by ltratt** [comment]
Please squash.

**Comment by vext01** [comment]
splat.

**Comment by vext01** [comment]
I wish I'd waited for this to merge before merging your PR :P

**Comment by ltratt** [comment]
Ha! Please force push an update.

**Comment by vext01** [comment]
Done.

**Comment by vext01** [comment]
This is going to fail in release mode.

I matched asm in a test, but stringifying asm is only avaliable in debug mode (because it's expensive).

Shall I remove the asm matching?

**Comment by ltratt** [comment]
Or make it only run in debug mode?

**Comment by vext01** [comment]
Indeed.

I think testing in release mode is more important.

Maybe a later PR can make asm stringifying available in release mode. It should only be used in tests and for debugging anyway...

**Comment by ltratt** [comment]
Now I'm confused about what you want to do right now :)

**Comment by vext01** [comment]
I'll push a commit to explain.

**Comment by vext01** [comment]
See https://github.com/ykjit/yk/pull/1117/commits/986598beecdab864f273ccad04e775b65be17778

**Comment by vext01** [comment]
Yes, we could, but then we don't test sign extends in release mode at all.

If we remove the asm matching, then we can test both modes, which I think is more valuable. Don't you agree?

**Comment by vext01** [comment]
Yeah, that's another option.

But I wonder why we guard the jit-asm phase at all. Yeah, it's expensive (disassembly), but it's only used if you ask for it.

**Comment by ltratt** [comment]
> But I wonder why we guard the jit-asm phase at all. Yeah, it's expensive (disassembly), but it's only used if you ask for it.

Then unguard it as part of this PR?

**Comment by vext01** [comment]
Can do. I'm just a little twitchy as this is now blocking other PRs. Let me see if I can do it quick.

**Comment by vext01** [comment]
In light of this, do you mind if I force push a git history that would make more sense.

**Comment by ltratt** [comment]
Can we do the release mode commit first? I don't like pushing new code in a rebase.

**Comment by vext01** [comment]
OK. I'll pray that I can move the commit earlier.

**Comment by vext01** [comment]
Ugh, I can see why I guarded this stuff.

To sanely match jit-asm you need comment lines in the trace, which are stored in a hashmap. We'd be incurring the cost of inserting/storing the hashmap in release mode, even if it isn't used.

See https://github.com/ykjit/yk/pull/1117/commits/2ef52161adb767d54ab6583b27ed85023ffda8dc

I'm not sure this is what we want.

What shall we do?

**Comment by vext01** [comment]
re comment lines. Imagine writing a lang test for this without comment lines:
```
; prologue                                                                                                                                                                                                                                    
00007f76a408b000 00000000: push rbp                                                                                                                                                                                                           
00007f76a408b001 00000001: mov rbp, rsp                                                                                                                                                                                                       
00007f76a408b004 00000004: push rdi                                                                                                                                                                                                           
00007f76a408b005 00000005: push rsi                                                                                                                                                                                                           
00007f76a408b006 00000006: mov rbp, rsp                                                                                                                                                                                                       
00007f76a408b009 00000009: sub rsp, 0xB0                                                                                                                                                                                                      
; Breakpoint hack                                                                                                                                                                                                                             
00007f76a408b010 00000010: mov r11, 0x7F76A3C8BB20                                                                                                                                                                                            
00007f76a408b01a 0000001a: call r11                                                                                                                                                                                                           
; %0: ptr = Arg(0)                                                                                                                                                                                                                            
00007f76a408b01d 0000001d: mov [rbp-0x08], rdi                                                                                                                                                                                                
; %1: ptr = LoadTraceInput 32, ptr                                                                                                                                                                                                            
00007f76a408b024 00000024: mov r12, [rdi+0x20]                                                                                                                                                                                                
00007f76a408b02c 0000002c: mov [rbp-0x10], r12                                                                                                                                                                                                
; %2: ptr = LoadTraceInput 24, ptr                                                                                                                                                                                                            
00007f76a408b033 00000033: mov r12, [rdi+0x18]                                                                                                                                                                                                
00007f76a408b03b 0000003b: mov [rbp-0x18], r12                                                                                                                                                                                                
; %3: ptr = LoadTraceInput 16, ptr                                                                                                                                                                                                            
00007f76a408b042 00000042: mov r12, [rdi+0x10]                                                                                                                                                                                                
00007f76a408b04a 0000004a: mov [rbp-0x20], r12                                                                                                                                                                                                
; %4: ptr = LoadTraceInput 8, ptr                                                                                                                                                                                                             
00007f76a408b051 00000051: mov r12, [rdi+0x08]                                                                                                                                                                                                
00007f76a408b059 00000059: mov [rbp-0x28], r12                                                                                                                                                                                                
; %5: ptr = LoadTraceInput 0, ptr                                                                                                                                                                                                             
00007f76a408b060 00000060: mov r12, [rdi]                                                                                                                                                                                                     
00007f76a408b068 00000068: mov [rbp-0x30], r12                                                                                                                                                                                                
; TraceLoopStart                                                                                                                                                                                                                              
; %7: ptr = LookupGlobal shadowstack_0                                                                                                                                                                                                        
00007f76a408b06f 0000006f: mov r12, 0x204108               
00007f76a408b079 00000079: mov [rbp-0x38], r12             
...
```

**Comment by vext01** [comment]
I agree. This is blocking PRs, so let's mull it over.

**Comment by ltratt** [comment]
Please squash.

**Comment by vext01** [comment]
Of course now there are conflicts.

**Comment by vext01** [comment]
Can I force push to fix this?

**Comment by ltratt** [comment]
Please go ahead.

**Comment by vext01** [comment]
done.

**Pull request merged**
