### PR TITLE
Add/fix tests for new shadow stack allocation scheme.

### PR DESCRIPTION
**Pull request by vext01**
Requires https://github.com/ykjit/ykllvm/pull/220 (and a ykllvm sync)

### CODE REVIEW

**Comment by ltratt** [comment]
Please force push a ykllvm sync.

**Comment by vext01** [comment]
I rebased, synced ykllvm and force pushed.

(The "compare" contains what I assume is the result of the rebase, so may contain more than you expected)

**Comment by vext01** [comment]
hold off this for a moment, just realised the rebase causes test failures.

**Comment by vext01** [comment]
test fixed with another force push.

**Comment by ltratt** [comment]
*Probably* this means that we can delete `peel1.swt.c` and remove ` || test "$YKB_TRACER" = "swt"` from `peel1.c`. In other words, we can probably use one test for both hwt and swt, which would be nice!

**Comment by vext01** [comment]
test seems to pass, so great.

**Comment by vext01** [comment]
(force pushed, btw)

**Comment by ltratt** [comment]
Thanks!

**Pull request merged**
