### PR TITLE
Partially implement fp_to_si.

### PR DESCRIPTION
**Pull request by vext01**
This allows the lua test suite to run to completion (with serialised compilation).

Requires https://github.com/ykjit/ykllvm/pull/179

### CODE REVIEW

**Comment by ltratt** [comment]
> with serialised compilation

Just to check: it also works with serialised compilation off, right? [I appreciate that serialised compilation in some senses tests more of the pipeline, but I wanted to be sure.]

**Comment by vext01** [comment]
I hadn't tested it previously, but yes it does (tested with debug build only).

(At this stage we are probably exiting before traces get a chance to compile?)

**Comment by vext01** [comment]
> (At this stage we are probably exiting before traces get a chance to compile?)

Yep. Just checked. No traces are executed if you don't serialise compilation.

**Comment by ltratt** [comment]
Got it.

Can we add yklua (the current HEAD commit on `main`) to `.buildbot.sh` as part of this PR?

**Comment by vext01** [comment]
Mind if we do it in the next PR, so that others can run a complete test suite in the meantime?

**Comment by ltratt** [comment]
I don't mind doing it in the next PR but I don't know what "others can run a complete test suite in the meantime" means.

**Comment by vext01** [comment]
Just means the test suite can be run to completion while I prepare the change.

**Comment by ltratt** [comment]
Agreed offline about not adding yklua tests into this PR.

@vext01 When the ykllvm PR merges can you force push an update to the ykllvm merge commit in this PR? It will save us well over an hour of CI time.

**Comment by vext01** [comment]
Ah, because we cache the previous commit? That's unfortunate.

**Comment by ltratt** [comment]
ykllvm caching will do so on the merge commit. So when this PR merges there won't be a cache hit, so this PR takes ~45-50 mins to merge, then we realise that the ykllvm we care about wasn't cached, and do so then.

Everything works in either case, but I think we'll have several yk PRs merging today, so it's probably good not to tie CI up for so long.

**Comment by vext01** [comment]
OK, so in the future I won't prepare the PR with an LLVM sync from the outset.

**Comment by ltratt** [comment]
I don't want to make our lives too complex here. In fact, in retrospect, I think I should have kept my mouth shut! Let's just let CI do its thing as-is without force pushing. After lunch it'll catch up this.

**Pull request merged**
