### PR TITLE
Allow us to trace binaries compiled with -g.

### PR DESCRIPTION
**Pull request by vext01**
The first commit is the main body of work. The second is tidying.

### CODE REVIEW

**Comment by ptersilie** [comment]
Just a typo in in the second commit message: s/it's/its. Did you also run `cargo xtask cfmt` already. I saw something that I'm not sure would be caught by the formatter. You can squash any formatting right away.

**Comment by vext01** [comment]
`cargo xtask cfmt` doesn't change anything. Which line is suspect?

**Comment by ptersilie** [comment]
Nevermind then. :-D Just the typo to fix then.

**Comment by vext01** [comment]
okie dokie. Commit message fixed.

**Pull request merged**
