### PR TITLE
Move raw trace -> IR trace mapping into a compilation thread.

### PR DESCRIPTION
**Pull request by ltratt**
**DRAFT PR: DO NOT MERGE!**

Previously the HW tracer did the mapping immediately after stopping PT, stalling the rest of the system while the (potentially very slow) mapping was computed.

This commit returns the unmapped trace, allowing the compilation thread to do the mapping itself.

@ptersilie can you see if this solves the stalling problem you were seeing? If so, I will go through and tidy this up before making the final PR.

### CODE REVIEW

**Comment by ptersilie** [comment]
Yes, this works and allows my ykcbf test to finish running now. Though I'm not sure how useful that test is now, since we are likely never seeing a compiled trace. At least not until we filter out obviously large traces before they are being decoded.

**Comment by vext01** [comment]
This looks pretty inoffensive to me :)

**Comment by ltratt** [comment]
Squashed.

**Comment by ptersilie** [comment]
Hah, all because a missing (and irrelevant) `,`. :D

**Comment by ltratt** [comment]
Sausages. OK to squash?

**Comment by ptersilie** [comment]
Please squash.

**Pull request merged**
