### PR TITLE
local_key_cell_methods has not been needed as of rust 1.73.0-nightly.

### PR DESCRIPTION
**Pull request by ltratt**

### CODE REVIEW

**Comment by ltratt** [comment]
https://github.com/ykjit/yk/pull/814/commits/6dc088c1d7f677ba79ff94a3a5d8effa6e83ad27 resolves the merge conflict. OK to squash?

**Comment by ptersilie** [comment]
Please squash.

**Comment by ltratt** [comment]
Squashed.

**Pull request merged**
