### PR TITLE
Parse more jit ir

### PR DESCRIPTION
**Pull request by ltratt**
Needs https://github.com/ykjit/yk/pull/1196 to be merged first.

This PR starts to show why the JIT IR parser makes our life easier. I've added support for several JIT IR constructs and ported over a number of tests in the x86 backend as examples.

### CODE REVIEW

**Comment by ltratt** [comment]
OK to rebase against master?

**Comment by vext01** [comment]
Please rebase.

**Comment by ltratt** [comment]
Rebased.

**Comment by ltratt** [comment]
Closing as I'm going to open a more extensive PR along these lines later.

**Pull request closed without merging**
