### PR TITLE
Simplify reading in the (raw) .llvmbc section.

### PR DESCRIPTION
**Pull request by vext01**
61cfd3a is the main commit. See commit messages.

### CODE REVIEW

**Comment by ltratt** [comment]
This may be a very silly question but I had always vaguely thought (without ever bothering to check) that the whole executable is in a sense mmap'd into memory by default? Or does the linker actually only load in the sections that "do something useful"?

**Comment by vext01** [comment]
The linker will only load in the segments marked `PT_LOAD`, so not the whole binary.

Lukas and I spent a while (a month or so ago) trying to get the bitcode to be marked in such a way, but ended up doing it this way to just get going.

We could add a `PERF` comment actually?

**Comment by vext01** [comment]
Any further comments on this one?

**Comment by ltratt** [comment]
> We could add a PERF comment actually?

Good idea!

**Comment by vext01** [comment]
I've added a couple of comments, as there are two places where we could apply a similar optimisation.

**Comment by vext01** [comment]
OK to squash?

**Comment by ltratt** [comment]
Please squash.

**Comment by vext01** [comment]
Splat.

**Comment by vext01** [comment]
Looks like our threading still isn't right.

**Comment by vext01** [comment]
I'm unable to reproduce this, even when bumping the loop bounds in the test and having it run for hours.

What do you think we should do? Try again and keep a close eye on this?

**Comment by ltratt** [comment]
Oh hang on.

bors r-

**Comment by ltratt** [comment]
Sorry, I thought you meant this was some sort of weird OS error. But it's one of our tests failing. I fear that we need to work out what's going on here. Let's try again to see if at least happens again under bors, which might help give you some clues?

bors try

**Comment by vext01** [comment]
19ae71a seems to fix the threading issue.

9a5e3d0 is mostly unrelated, but it might have made debugging easier.

I need to sync the branch before this will merge due to Lukas' block map change. OK to do that with the squash?

**Comment by ltratt** [comment]
Please squash.

**Comment by vext01** [comment]
2e492ea deals with the braces. OK to squash and sync?

**Comment by ltratt** [comment]
Please squash.

**Comment by vext01** [comment]
splat.

**Pull request merged**
