### PR TITLE
Tidy test infra

### PR DESCRIPTION
**Pull request by vext01**
See commits.

### CODE REVIEW

**Comment by ltratt** [comment]
Good point: we got rid of `YK_JIT_COMPILER` in 08bb97d13c2ad471eb90670003a06f5a405fbc81.

**Comment by vext01** [comment]
OK to squash?

**Comment by ltratt** [comment]
Please squash + rebase.

**Comment by vext01** [comment]
squashed and rebased.

**Comment by vext01** [comment]
Force pushed a fix.

**Comment by ltratt** [comment]
Can we briefly outline what the fix was? e.g. formatting etc

**Comment by ltratt** [comment]
Please squash.

**Comment by vext01** [comment]
squashed.

**Pull request merged**
