### PR TITLE
Enable outlining of calls in the trace builder.

### PR DESCRIPTION
**Pull request by ptersilie**
Depends on https://github.com/ykjit/ykllvm/pull/138 and requires a change to the submodule once that is merged.

### CODE REVIEW

**Comment by vext01** [comment]
go ahead.

**Comment by vext01** [comment]
LGTM

**Comment by ptersilie** [comment]
Ok to squash?

**Comment by vext01** [comment]
Sorry, yes go ahead.

**Comment by ptersilie** [comment]
Squashed.

**Pull request merged**
