### PR TITLE
Rename ykllvmwrap to yktracec.

### PR DESCRIPTION
**Pull request by ltratt**
As discussed a couple of weeks back. Best to wait for https://github.com/ykjit/yk/pull/681 to be merged first.

### CODE REVIEW

**Comment by vext01** [comment]
Nothing controversial here. Once the other PR is done, this can go in I think.

**Comment by ltratt** [comment]
OK for me to force push a rebase?

**Comment by ltratt** [comment]
Rebased (I don't know why github said there were conflicts -- rebase didn't complain at all).

**Pull request merged**
