### PR TITLE
Simplify code that passes the stackmap pointer and size into the trace.

### PR DESCRIPTION
**Pull request by vext01**
I think this is correct, but I would like @ptersilie to check.

### CODE REVIEW

**Comment by ltratt** [comment]
An obvious question: does the receiving side of this change (i.e. the compiled trace) expect a "64 bit" (specifically) input or `uintptr_t` equivalent?

**Comment by vext01** [comment]
My change was purely mechanical, but looking deeper....

The code I changed is the code which generates the parent function of the JITted code.

This is called from Rust here:
https://github.com/ykjit/yk/blob/2e0ad668350f526144169e5cda17f552474ef350/yktrace/src/lib.rs#L192-L194

Where:
https://github.com/ykjit/yk/blob/2e0ad668350f526144169e5cda17f552474ef350/yktrace/src/lib.rs#L169-L172

So it appears that these two parameters need to be pointer sized, hence the variability per-platform.

**Comment by ltratt** [comment]
> So it appears that these two parameters need to be pointer sized, hence the variability per-platform.

I don't understand this sentence.

**Comment by vext01** [comment]
The two arguments in question are passed at the call site as `*const c_void` (pointer-sized) and `usize` (also pointer-sized).

This is why we can't use fixed-size argument types for all platforms when generating the JITted code function.

**Comment by ltratt** [comment]
I understand your statements in isolation but I can't relate them to the PR: `uintptr_t` and equivalent aren't fixed size.

Put another way: is your comment in https://github.com/ykjit/yk/pull/482#issuecomment-1027826061 saying "this means the PR is wrong" or ... ?

**Comment by vext01** [comment]
I believe the change to remain correct.

**Comment by ltratt** [comment]
OK, so I can just ignore https://github.com/ykjit/yk/pull/482#issuecomment-1027826061 then?

**Comment by ltratt** [comment]
After offline discussion, I now understand that https://github.com/ykjit/yk/pull/482#issuecomment-1027826061 was answering my question in https://github.com/ykjit/yk/pull/482#issuecomment-1027815141 in a good way :)

bors r+

**Comment by ptersilie** [comment]
Looks good to me.

**Comment by vext01** [comment]
My bad. OK to squash?

**Comment by ltratt** [comment]
Please squash.

**Comment by vext01** [comment]
splat.

**Pull request merged**
