### PR TITLE
Optimise guards of a constant value

### PR DESCRIPTION
**Pull request by ltratt**
The ultimate destination of this PR is https://github.com/ykjit/yk/commit/791c89d2ddde53218bf2a0e352895a91a9d3c9e7, which optimises away guards in JIT IR if they reference a constant. Before doing that, over several commits, we introduce more careful well-formedness checks that ensure guards are of the right shape.

### CODE REVIEW

**Comment by ptersilie** [comment]
A langtest that uses `i8` is failing.

**Comment by ltratt** [comment]
Oops! Fixed in 551c6a41258ece6000311a7f5b7a17441047deff.

**Comment by ptersilie** [comment]
Please squash.

**Comment by ltratt** [comment]
Squashed.

**Pull request merged**
