### PR TITLE
Run CI inside docker

### PR DESCRIPTION
**Pull request by vext01**
See commits.

Depends on https://github.com/softdevteam/buildbot_config/pull/69

### CODE REVIEW

**Comment by vext01** [comment]
bors r-

Sorry, snare failed on the buildbot config.

**Comment by vext01** [comment]
You can retry this now.

**Comment by vext01** [comment]
The build finished, but this didn't merge:
https://ci.soft-dev.org/#/builders/1/builds/2089

Investigating...

**Comment by ltratt** [comment]
Please squash.

**Comment by vext01** [comment]
Actually, these make sense separate. Go ahead.

**Pull request merged**
