### PR TITLE
Migrate some old tests

### PR DESCRIPTION
**Pull request by vext01**
Wave one of migrating old tests.

Some tests were improved along the way. Some were unmarked `ignore-if` because they now work (or i could fix them easily). One turned out unnecessary. 3 tests crash and are marked `ignore-if`.

36 to go after this.

### CODE REVIEW

**Comment by ltratt** [comment]
This will need rebasing after https://github.com/ykjit/yk/pull/1352. If you're lucky git will patch things for you. If not, you might need to rename a few `yk_mt_drop`s in C code to `yk_mt_shutdown`.

**Comment by ltratt** [comment]
Please force push a rebase if/when #1352 merges.

**Comment by ltratt** [comment]
Please force push a rebase.

**Comment by vext01** [comment]
rebased, but something seems to have gone wrong. One moment.

**Comment by vext01** [comment]
There we go. Rebased properly this time :)

**Pull request merged**
