### PR TITLE
Check C formatting in bors using xtask cfmt.

### PR DESCRIPTION
**Pull request by ptersilie**

### CODE REVIEW

**Comment by ptersilie** [comment]
bors try

**Comment by ptersilie** [comment]
Okay, this works. But now I'm wondering it's not better to use `git diff --exit-code` instead, so we can see the diff in the bors output.

**Comment by ltratt** [comment]
> But now I'm wondering it's not better to use git diff --exit-code instead, so we can see the diff in the bors output.

Good idea -- let's try it!

**Comment by ptersilie** [comment]
This is ready for review now.

**Comment by vext01** [comment]
Please squash.

**Comment by ptersilie** [comment]
I'm afraid that if I squash any more there won't be any commits left. ;-)

**Comment by vext01** [comment]
Outrageous!

bors r+

**Pull request merged**
