### PR TITLE
This argument doesn't need to be mutable.

### PR DESCRIPTION
**Pull request by ltratt**

### CODE REVIEW

**Comment by vext01** [comment]
Line 87 looks like mutation to me...

**Comment by ltratt** [comment]
I see what you mean: depending on the config, we get `mut` warnings or not. FWIW, I think `YKD_FORCE_TRACE_DECODER` should be killed, as it suggests a global option when it's really PT specific. OK for me to remove it?

**Comment by vext01** [comment]
> PT specific

PT specific in that we only have a PT decoder, if that's what you mean? It was intended to be general.

You can kill it if you want, but you may end up bringing it back when we have other kinds of decoder?

**Comment by vext01** [comment]
Ah, just kill it -- we can add it back if need be.

**Comment by ltratt** [comment]
I'll close this PR and open a new one with better info.

**Pull request closed without merging**
