### PR TITLE
Try to slightly reduce CI time

### PR DESCRIPTION
**Pull request by ltratt**
https://github.com/ykjit/yk/commit/ec6fe710f6ca07c1511bb6a51245f05a3558552b is the main meat of the PR.

### CODE REVIEW

**Comment by vext01** [comment]
One comment on a commit.

**Comment by ltratt** [comment]
Oops! Fixed in 6d9fb825.

**Comment by vext01** [comment]
Please squash.

**Comment by ltratt** [comment]
Oops again. Fixed in 3e97b5b8.

**Comment by vext01** [comment]
Squash away

**Comment by ltratt** [comment]
Squashed.

**Pull request merged**
